name: API Pipeline on Testing Env  # Workflow name

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman (Postman CLI)
        run: npm install -g newman

      # Run Collection 1
      - name: Run Testing intervals singleShift summary report
        run: |
          newman run ./Collections/Testing-summaryReport-All-Employees.postman_collection.json \
          -e ./Environments/testing.postman_environment.json \
          -d ./TestingDataFiles/workSummaryReportAllEmployees.json \
          -r cli
